<?php
    use Lns\Sb\Lib\Lang\Lang;
    $_lang = new Lang();
?>
<div class="signin-container">
    <div class="offset-4 col-md-4 peer pX-40 pY-80 h-100 scrollable pos-r" style="min-width:320px">
        <h4 class="text-center fw-600 c-grey-900 mB-0"><?= $_lang->getLang('forgot_your_password'); ?></h4>
        <h6 class="text-center fw-300 c-grey-900 mB-25"><?= $_lang->getLang('enter_your_email_address_below'); ?></h6>
        <div class="signinform-wrapper">
            <!-- STEP 1 -->
            <div class="forgotpasswordform" data-type="1">
                <form>
                    <div class="form-group">
                        <label class="text-normal text-dark"><?= $_lang->getLang('email'); ?></label>
                        <input type="email" class="form-control" name="email" placeholder="juan.delacruz@gmail.com">
                    </div>
                </form>
                <div class="form-group mb-1">
                    <button class="proceed btn btn-success form-control"><?= $_lang->getLang('send_me_the_code'); ?></button>
                </div>
                <div class="form-group mb-0">
                    <button class="back btn btn-secondary form-control"><?= $_lang->getLang('cancel'); ?></button>
                </div>
            </div>

            <!-- STEP 2 -->
            <div class="d-none forgotpasswordform" data-type="2">
                <form>
                    <div class="form-group">
                        <label class="text-normal text-dark"><?= $_lang->getLang('code'); ?></label>
                        <input type="text" class="form-control" name="code" placeholder="xxxxxx">
                    </div>
                </form>
                <div class="form-group mb-1">
                    <button class="proceed btn btn-success form-control"><?= $_lang->getLang('verify_code'); ?></button>
                </div> 
                <div class="form-group mb-0">
                    <button class="back btn btn-secondary form-control"><?= $_lang->getLang('go_back'); ?></button>
                </div>
            </div>

            <!-- STEP 3 -->
            <div class="d-none forgotpasswordform" data-type="3">
                <form>
                    <div class="form-group">
                        <label class="text-normal text-dark"><?= $_lang->getLang('new_password'); ?></label>
                        <input type="password" class="form-control" name="password">
                    </div>
                    <div class="form-group">
                        <label class="text-normal text-dark"><?= $_lang->getLang('retype_password'); ?></label>
                        <input type="password" class="form-control" name="retype_password">
                    </div>
                </form>
                <div class="form-group mb-1">
                    <button class="proceed btn btn-success form-control"><?= $_lang->getLang('change_your_password'); ?></button>
                </div> 
                <div class="form-group mb-0">
                    <button class="back btn btn-secondary form-control"><?= $_lang->getLang('go_back'); ?></button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- NOTE: PLEASE TRANSFER THESE CODES -->
<script>
//forgotpasswordform
    require(['jquery'], function($){
        $.ajax({
            url: '<?php echo $this->getUrl("/api/token/get_token"); ?>',
            method: 'post',
            data: {
                appKey: '<?php echo Lns\Sb\Controller\Controller::APPKEY ?>',
            },
            success: function(data){
                if(data.error == 0){
                    localStorage.token = data.token;
                    localStorage.api_secret = data.api_secret;
                }
            }
        });

        $('.signinform-wrapper').delegate('.forgotpasswordform:not(.d-none) button.proceed', 'click', function(){
            var container = $(this).parent().parent();
            var form = container.find('form');
            var type = container.attr('data-type');

            var data = {};
            $.each(form.serializeArray(), function(index, element){
                data[element.name] = element.value
            });
            data.type = type;

            $.ajax({
                url: '<?php echo $this->getUrl("/api/user/forgot_password"); ?>',
                method: 'POST',
                data: data, 
                headers: {
                    authorization: 'Bearer ' + localStorage.token,
                    apiSecret: localStorage.api_secret
                },
                success: function(response){
                    if(response.error == 0){
                        if(type != 3){
                            if(type == 1){
                                localStorage.token = response.token;
                            }
                            container.addClass('d-none');
                            container.next().removeClass('d-none');
                        } else{
                            window.location.replace('<?php echo $this->getAdminUrl("login"); ?>');
                        }
                    } else{
                        alert(response.message);
                    }
                    
                    console.log(response);
                }
            });
        });

        $('.signinform-wrapper').delegate('.forgotpasswordform:not(.d-none) button.back', 'click', function(){
            var container = $(this).parent().parent();
            var type = container.attr('data-type');

            if(type == 1){
                window.location.replace('<?php echo $this->getAdminUrl("login"); ?>');
            } else{
                container.addClass('d-none');
                container.prev().removeClass('d-none');
            }
        });
    });
</script>

