<h3>Change Password</h3>
<form class="changepasswordform">
    <label for="current_password">Current Password</label>
    <input type="password" name="current_password" id="current_password">
    <br>
    <label for="new_password">New Password</label>
    <input type="password" name="new_password" id="new_password">
    <br>
    <label for="confirm_password">Confirm Password</label>
    <input type="password" name="confirm_password" id="confirm_password">
    <br>
</form>

<button class="sample">Click Me.</button>


<!-- NOTE: PLEASE TRANSFER THESE CODES. THIS JUST FOR TESTING PURPOSES ONLY. -->
<script>
    require(['jquery'], function($){
        $('.sample').on('click', function(){
            var data = {
                    current_password : $('#current_password').val(),                    
                    new_password : $('#new_password').val(),
                    confirm_password : $('#confirm_password').val()
                };

            $.ajax({
                url: "<?php $this->getAdminUrl('users/userprofile/changepassword') ?>",
                method: 'post',
                data: data,
                success: function(data){
                    console.log(data);
                }
            });
        });
    });
</script>
<!-- END: NOTE -->