<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="ModalLongTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-md" role="document">
        <div class="modal-content">
            <form id="confirm-form-action" action="" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="ModalLongTitle"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="confirmQuestion">
                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn cur-p btn-outline-secondary" data-dismiss="modal">Cancel</button>
                    <input id="confirm_id" type="hidden" name="id" value="">
                    <button id="confirmButton" class="btn cur-p btn-primary" value="1" name="confirm"></button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- REMINDER: PLEASE TRANSFER THESE CODES FOR CLEANER OUTPUT -->
<script>
    require([
        'jquery',
        'lns/sb/admin/js/confirmation.modal.min'
    ], function($) {
        
    });
</script>