<?php
	use Lns\Sb\Lib\Lang\Lang;
	$permission = $this->getPermission();
	$_lang = new Lang();
?>
<div class="row">
    <div class="col-md-12">
    	<div class="clearfix mB-20">
			<h4 class="c-grey-900 mB-0 pull-left"><?= $permission ? 'Edit Permission' : 'Create New Permission' ?></h4>	
			<a href="<?= $this->getAdminUrl('/permissions') ?>">
				<button type="button" class="btn cur-p btn-success pull-right">
					<?= $_lang->getLang('back'); ?>
				</button>
			</a>
		</div>
    </div>

    <div class="col-sm-6 col-md-6 col-lg-6">
		<div class="card bd bdrs-3 pX-30 pY-25 mB-20 mB-20">
			<h6 class="c-grey-900 mB-20"><?= $_lang->getLang('permission_fields'); ?></h6>
			<form action="<?= $this->getAdminUrl('permissions/action/save') ?>" method="POST">
				<input type="hidden" name="id" value="<?= $permission ? $permission->getData('id') : '' ?>" />
				
				<div class="form-group">
					<label for="permissions-name"><?= $_lang->getLang('permission_name'); ?></label>
					<input 
						type="text" 
						class="form-control" 
						id="permissions-name" 
						name="name" 
						value="<?= $permission ? $permission->getData('name') : '' ?>" 
						required="required"
					/>
				</div>
				
				<div class="form-group">
					<label for="permissions-code"><?= $_lang->getLang('code'); ?></label>
					<input 
						type="text" 
						class="form-control" 
						id="permissions-code" 
						name="code" 
						value="<?= $permission ? $permission->getData('code') : '' ?>" 
						required="required"
					/>
				</div>

				<div class="form-group">
					<label for="permissions-description"><?= $_lang->getLang('permission_description'); ?></label>
					<textarea 
						class="form-control" 
						id="permissions-description" 
						name="description" 
						required="required" 
					><?= $permission ? $permission->getData('description') : '' ?></textarea>
				</div>

				<div class="form-group row">
					<div class="col-sm-10">
						<button type="submit" class="btn btn-primary" value="1" name="save">
							<?= $_lang->getLang('save'); ?>
						</button>
					</div>
				</div>
			</form>
    	</div>
	</div>
</div>