<?php
	use Lns\Sb\Lib\Lang\Lang;
	$role = $this->getRole();
	$_lang = new Lang();
?>
<div class="row">
    <div class="col-md-12">
    	<div class="clearfix mB-20">
			<h4 class="c-grey-900 mB-0 pull-left"><?= $role ? 'Edit Role' : 'Create New Role' ?></h4>	
			<a href="<?= $this->getAdminUrl('/roles') ?>">
				<button type="button" class="btn cur-p btn-success pull-right">
					<?= $_lang->getLang('back'); ?>
				</button>
			</a>
		</div>
    </div>

    <div class="col-sm-6 col-md-6 col-lg-6">
		<div class="card bd bdrs-3 pX-30 pY-25 mB-20 mB-20">
			<h6 class="c-grey-900 mB-20"><?= $_lang->getLang('role_fields'); ?></h6>
			<form action="<?= $this->getAdminUrl('roles/action/save') ?>" method="POST">
				<input type="hidden" name="id" value="<?= $role ? $role->getData('id') : '' ?>" />
				
				<div class="form-group">
					<label for="roles-name"><?= $_lang->getLang('role_name'); ?></label>
					<input 
						type="text" 
						class="form-control" 
						id="roles-name" 
						name="name" 
						value="<?= $role ? $role->getData('name') : '' ?>" 
						required="required"
					/>
				</div>

				<div class="form-group">
					<label for="roles-description"><?= $_lang->getLang('role_description'); ?></label>
					<textarea 
						class="form-control" 
						id="roles-description" 
						name="description" 
						required="required" 
					><?= $role ? $role->getData('description') : '' ?></textarea>
				</div>

				<div class="form-group row">
					<div class="col-sm-10">
						<button type="submit" class="btn btn-primary" value="1" name="save">
							<?= $_lang->getLang('save'); ?>
						</button>
					</div>
				</div>
			</form>
    	</div>
	</div>
</div>

