<div style="width: 100%; padding: 15px; box-sizing: border-box; min-width: 320px; position: relative; background: #f2f2f2; ">
	<div style="
		max-width: 426px !important; 
		margin-top: 45px; 
		margin-left: auto; 
		margin-right: auto; 
		min-height: 150px; background: #ffffff; border-radius: 5px !important; 
		-webkit-box-shadow: 0px 0px 13px 2px rgba(0,0,0,0.23) !important; 
		-moz-box-shadow: 0px 0px 13px 2px rgba(0,0,0,0.23) !important; 
		box-shadow: 0px 0px 13px 2px rgba(0,0,0,0.23) !important; 
	">
		<div style="height: 102px;padding: 40px 15px 0px 15px;box-sizing: border-box;text-align: center;">
			<img src="<?= $this->_url->getUrl('/assets/sbc/images/static/sbc_mail_logo.png') ?>" />
		</div>
		<div style="padding: 40px 30px;font-family: arial;font-size: 14px;line-height: 1.3em;">
			<?= $messageBody ?>
		</div>
		<div style="background: #ffffff;height: 106px;border-bottom-left-radius: 5px;border-bottom-right-radius: 5px;padding: 30px 15px 0px 15px;box-sizing: border-box; border-top: 1px solid #f2f2f2;">
			<?php if($sender->email): ?>
				<p style="margin: 0px 0px 0px 0px;display: block;text-align: center;font-family: arial;font-size: 12px;">
					If you want to reply back, you can message me at:
				</p>
				<p style="margin: 10px 0px 0px 0px;text-align: center;font-size: 18px;font-family: arial;color: #3884d5;">
					<?= $sender->email ?>
				</p>
			<?php endif ?>
		</div>
	</div>
		
	<div style="max-width: 426px;margin: 0px auto 0 auto !important;min-height: 150px;padding: 15px;box-sizing: border-box;text-align: center;">
		<ul style="margin: ;padding: 0;list-style: none;margin: 20px 0px 20px 0px;">
			<li style="display: inline-block;margin-right: 10px;">
				<a href="">
					<img src="<?= $this->_url->getUrl('/assets/sbc/images/static/icon.facebook.png') ?>" />
				</a>
			</li>
			<li style="display: inline-block;margin-right: 10px;">
				<a href="">
					<img src="<?= $this->_url->getUrl('/assets/sbc/images/static/icon.tweeter.png') ?>" />
				</a>
			</li>
			<li style="display: inline-block;margin-right: 10px;">
				<a href="">
					<img src="<?= $this->_url->getUrl('/assets/sbc/images/static/icon.instagram.png') ?>" />
				</a>
			</li>
			<li style="display: inline-block;">
				<a href="<?= $this->_url->getUrl(); ?>">
					<img src="<?= $this->_url->getUrl('/assets/sbc/images/static/icon.website.png') ?>" />
				</a>
			</li>
		</ul>
		<div style="border-top: solid 1px #e8ebef;box-sizing: border-box;padding: 22px 0;">
			<p style="margin: 0;font-size: 11px;font-family: arial;color: #666666;">
				You’re receiving this message because you signed up to SportBizCon.</p>
			<p style="font-size: 11px;color: #666666;font-style: italic;">
				Copyright © SportBizCon, All Rights Reserved
			</p>
		</div>
	</div>
</div>