<?php
// use Lns\Sb\Lib\Entity\Db\Users; 
use Lns\Sb\Lib\Entity\Db\Notification; 
use Of\Http\Request;

$_request = new Request();

// $_userModel = new Users($_request);
// $user = $_userModel->getLoggedInUser(); 
$_notificationModel = new Notification($_request);
$_notifications = $_notificationModel->getNotifications();
$total_notif = count($_notifications['datas']);
?>
<ul class="nav-right">
    <li class="notifications dropdown divider-left"><span class="counter bgc-red"><?= $total_notif ?></span> <a href="" class="dropdown-toggle no-after" data-toggle="dropdown"><i class="ti-bell"></i></a>
        <ul class="dropdown-menu">
            <li class="pX-20 pY-15 bdB"><i class="ti-bell pR-10"></i> <span class="fsz-sm fw-600 c-grey-900">Notifications</span></li>
            <li>
                <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
                    <?php
                        if($total_notif > 0){
                            foreach($_notifications['datas'] as $_notification){
                    ?>
                            <li>
                                <a href="<?= $_notification->getData('url'); ?>" class="peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100">
                                    <div class="peer mR-15"><img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt=""></div>
                                    <div class="peer peer-greed">
                                        <span>
                                            <?= $_notification->getData('data'); ?>
                                        </span>
                                        <p class="m-0"><small class="fsz-xs">5 mins ago</small></p>
                                    </div>
                                </a>
                            </li>
                    <?php        
                            }
                        }else{
                    ?>
                        <li class="py-3 text-center">
                            <span><i>No notification</i></span>
                        </li>
                    <?php
                        }
                    ?>
                    
                </ul>
            </li>
            <?php
                if($total_notif > 0){
            ?>
                <li class="pX-20 pY-15 ta-c"><span><a href="" class="c-grey-600 cH-blue fsz-sm td-n">View All Notifications <i class="ti-angle-right fsz-xs mL-10"></i></a></span></li>
            <?php
                }
            ?>
        </ul>
    </li>
    <li class="dropdown divider-left">
        <a href="" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-toggle="dropdown">
            <div class="peer mR-10"><img class="w-2r bdrs-50p" src="https://randomuser.me/api/portraits/men/10.jpg" alt=""></div>
            <!-- <div class="peer"><span class="fsz-sm c-grey-900"><?php //$user->getData('firstname') ?></span></div> -->
            <div class="peer"><span class="fsz-sm c-grey-900">John Doe</span></div>
        </a>
        <ul class="dropdown-menu fsz-sm">
            <!-- <li><a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700"><i class="ti-settings mR-10"></i> <span>Setting</span></a></li> -->
            <li><a href="<?= $this->getAdminUrl('users/userprofile') ?>" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700"><i class="ti-user mR-10"></i> <span>Profile</span></a></li>
            <!-- <li><a href="email.html" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700"><i class="ti-email mR-10"></i> <span>Messages</span></a></li> -->
            <li role="separator" class="divider"></li>
            <li><a href="<?= $this->getAdminUrl('logout') ?>" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700"><i class="ti-power-off mR-10"></i> <span>Logout</span></a></li>
        </ul>
    </li>
</ul>